Add Address Flag, Add flags to windows install

diff --git a/scripts/start_fair_registry b/scripts/start_fair_registry
--- a/scripts/start_fair_registry
+++ b/scripts/start_fair_registry
@@ -1,42 +1,54 @@
 #!/bin/bash
 
 PORT=8000
+ADDRESS="127.0.0.1"
 ORIGINAL_PWD=`pwd`
-case $1 in
-    -p|--port)
-        if [ -z "$2" ]; then
-            echo "No port provided."
-            exit 1
-        fi
-        PORT=$2
-        ;;
-    -h|--help)
-        echo "start_fair_registry [-p <port>]"
+
+while getopts ":a:address:p:port:h:help" opt; do
+  case $opt in
+    a|address) ADDRESS="$OPTARG"
+    ;;
+    p|port) PORT="$OPTARG"
+    ;;
+    h|help)
+        echo "start_fair_registry [-p <port>][-a <address>]"
         exit 0
-        ;;
-esac
+    ;;
+    \?) echo "Invalid option -${OPTARG} see -h" >&2
+    ;;
+  esac
+done
+
+FULL_ADDRESS="${ADDRESS}:${PORT}"
+
+if ! [[ "$PORT" =~ ^[0-9]+$ ]]; then
+    echo "Invalid port '$PORT' specified"
+    exit 1
+fi
 
 export DJANGO_SETTINGS_MODULE="drams.local-settings"
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
 FAIR_HOME="$(dirname "${DIR}")"
 cd $FAIR_HOME
 
-nohup "$FAIR_HOME"/venv/bin/python "$FAIR_HOME"/manage.py runserver $PORT > $FAIR_HOME/output.log 2>&1 &
+echo "Attempting to start Registry on ${FULL_ADDRESS}"
+nohup "$FAIR_HOME"/venv/bin/python "$FAIR_HOME"/manage.py runserver ${FULL_ADDRESS} > $FAIR_HOME/output.log 2>&1 &
 echo $PORT > $FAIR_HOME/session_port.log
+echo $ADDRESS> $FAIR_HOME/session_address.log
 
 count=0
-until [ $count -gt 6 ] || curl http://localhost:$PORT > /dev/null 2>&1
+until [ $count -gt 6 ] || curl http://${FULL_ADDRESS} > /dev/null 2>&1
 do
     sleep 1
     ((count++))
 done
 
-curl http://localhost:$PORT > /dev/null 2>&1
+curl http://${FULL_ADDRESS} > /dev/null 2>&1
 retVal=$?
 if [ $retVal -ne 0 ]; then
     echo Error starting local registry
 else
-    echo Local registry now accepting connections on http://localhost:$PORT
+    echo Local registry now accepting connections on http://${FULL_ADDRESS}
 fi
 
 "$FAIR_HOME"/venv/bin/python "$FAIR_HOME"/manage.py get_token > "$FAIR_HOME"/token
